//Users

GET http://localhost:3000/users

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Naruto",
  "password": "dasdasd"
}
###

GET http://localhost:3000/users/65102ced5e0fc1e931b89ab4

###


DELETE http://localhost:3000/users/65103a9d7bc6d320ffc28307

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jigglypuff",
  "age": 17,
  "password": "jiggly",
  "email": "dasdasd@gmail.com"
}

//Expenses

###

//Get user expenses
GET http://localhost:3000/expenses/653a222e8ade4cb129d8a44c

###
GET http://localhost:3000/expenses/expensesByDay/653a222e8ade4cb129d8a44c


###

//get expenses by category
GET http://localhost:3000/expenses/653a222e8ade4cb129d8a44c/expenses/Grocery

###
PATCH http://localhost:3000/expenses/653a222e8ade4cb129d8a44c
Content-Type: application/json

{
  "date": "2023-10-31",
  "category": "Gifts",
  "amount": 1130,
  "desc": ":("
}
 
###
DELETE http://localhost:3000/expenses/653a222e8ade4cb129d8a44c/expenses/65414d9b23af34d97e2cdcfc


//ExpensesCategories
###

POST http://localhost:3000/expensesCategories
Content-Type: application/json

{
  "name": "Bumbus",
  "color": "#FFFFFF"
}