//Users

GET http://localhost:3000/users

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Naruto",
  "password": "dasdasd"
}
{
  "name": "lukasz",
  "password": "Test@123"
}
###

GET http://localhost:3000/users/65102ced5e0fc1e931b89ab4

###


DELETE http://localhost:3000/users/65103a9d7bc6d320ffc28307

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jigglypuff",
  "age": 17,
  "password": "jiggly",
  "email": "dasdasd@gmail.com"
}

//Expenses

###

//Get user expenses
GET http://localhost:3000/expenses/653a222e8ade4cb129d8a44c

###
GET http://localhost:3000/expenses/expensesByDate/653a222e8ade4cb129d8a44c?startDate=2023-11-03&endDate=2023-11-30

###
GET http://localhost:3000/expenses/expensesByCategory/653a222e8ade4cb129d8a44c?startDate=2023-11-06&endDate=2023-11-30

###
//get expenses by category
GET http://localhost:3000/expenses/653a222e8ade4cb129d8a44c/expenses/Shopping

###
//get data for diagrams
GET http://localhost:3000/expenses/diagrams/653a222e8ade4cb129d8a44c

###
PATCH http://localhost:3000/expenses/653a222e8ade4cb129d8a44c
Content-Type: application/json

{
  "date": "2023-10-31",
  "category": "Gifts",
  "amount": 1130,
  "desc": ":("
}
 
###
DELETE http://localhost:3000/expenses/653a222e8ade4cb129d8a44c/expenses/6547bdfd49a4e3e3d87e1c07


//ExpensesCategories
###

POST http://localhost:3000/expensesCategories
Content-Type: application/json

{
  "name": "Bumbus",
  "color": "#FFFFFF"
}

###
GET http://localhost:3000/expensesCategories

###
//CRYPTO
GET http://localhost:3000/cryptocurrency/quote?crypto=BTC

###
GET http://localhost:3000/cryptocurrency/latest?limit=1

###
PATCH http://localhost:3000/assets/crypto/65f5ff49f8197629d2048b28
Content-Type: application/json

{
  "symbol": "JUP",
  "amount": 1500
}

###
GET http://localhost:3000/assets/crypto/65f5ff49f8197629d2048b28

###
PATCH http://localhost:3000/assets/crypto/65f5ff49f8197629d2048b28/65f602dcc78aa3dd323190ef
Content-Type: application/json

{
  "amount": 69
}